version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine@sha256:3c5c8892d184f738f4fe282d14ddaa613a38f00f4189d2d94725ebe6f2909ddb
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    build:
      context: .
      target: runtime-nginx
    restart: unless-stopped
    ports:
      - ${PORT}:80
    depends_on:
      - app
