version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine@sha256:890480b08124ce7f79960a9bb16fe39729aa302bd384bfd7c408fee6c8f7adb7
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    build:
      context: .
      target: runtime-nginx
    restart: unless-stopped
    ports:
      - ${PORT}:80
    depends_on:
      - app
