version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16-alpine@sha256:97ff59a4e30e08d1c11bdcd9455e7832368c0572b576c9092cde2df4ae5552a3
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nginx:
    build:
      context: .
      target: runtime-nginx
    restart: unless-stopped
    ports:
      - ${PORT}:80
    depends_on:
      - app
